### ISSUE TITLE
(lfurzewaddock/Coevery-Orchard) 'Reference Field' missing from 'Form Designer'

### ISSUE THREAD

**Issue by lfurzewaddock** [Coevery/Coevery#65]
Initial testing of lfurzewaddock/Coevery-Orchard fork code base as of commit:  https://github.com/lfurzewaddock/Coevery-Orchard/commit/89dba28b43b75eb5f5012987c7badb42a2dce287

Create a one-to-many relationship between 'Lead' entity and 'Opportunity' entity.

Follow the Coevery User Guide YouTube video https://www.youtube.com/watch?v=4g1N_P0-5WM until you are required to move the 'relatedopportunity' field in the Form Designer to below the 'CreateDate' field (10 min. 50 sec.). However, the 'relatedopportunity' reference field is missing and the following is logged;

2014-12-15 19:30:13,605 [65] Orchard.ContentManagement.Drivers.Coordinators.ContentFieldDriverCoordinator - RuntimeBinderException thrown from <>f__AnonymousType4`2 by <>f__AnonymousType4`2[[Orchard.ContentManagement.ContentPart, Orchard.Framework, Version=1.7.1.0, Culture=neutral, PublicKeyToken=null],[Coevery.Relationship.Fields.ReferenceField, Coevery.Relationship, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert type 'Coevery.Relationship.Fields.ReferenceField' to 'int?'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at lambda_method(Closure , Object )
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Coevery.Core.ContentPartFieldStorage.DefaultCotentPartFieldStorage.Get[T](String name)
   at Orchard.ContentManagement.FieldStorage.FieldStorageEventStorage.Get[T](String name) in d:\inetpub\vhosts\Orchard-Dev\1.7.1-Coevery-30-10-13\src\Orchard\ContentManagement\FieldStorage\IFieldStorageEvents.cs:line 38
   at Orchard.ContentManagement.FieldStorage.FieldStorageExtension.Get[T](IFieldStorage storage) in d:\inetpub\vhosts\Orchard-Dev\1.7.1-Coevery-30-10-13\src\Orchard\ContentManagement\FieldStorage\IFieldStorage.cs:line 8
   at Coevery.Relationship.Fields.ReferenceField.get_Value()
   at Coevery.Relationship.Drivers.ReferenceFieldDriver.Editor(ContentPart part, ReferenceField field, Object shapeHelper)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Orchard.ContentManagement.Drivers.ContentFieldDriver`1.<>c__DisplayClassd.<Orchard.ContentManagement.Drivers.IContentFieldDriver.BuildEditorShape>b__c(ContentPart part, TField field) in d:\inetpub\vhosts\Orchard-Dev\1.7.1-Coevery-30-10-13\src\Orchard\ContentManagement\Drivers\ContentFieldDriver.cs:line 34
   at Orchard.ContentManagement.Drivers.ContentFieldDriver`1.<>c__DisplayClass2d.<Process>b__2b(<>f__AnonymousType4`2 pf) in d:\inetpub\vhosts\Orchard-Dev\1.7.1-Coevery-30-10-13\src\Orchard\ContentManagement\Drivers\ContentFieldDriver.cs:line 86
   at Orchard.InvokeExtensions.<Invoke>d__0`2.MoveNext() in d:\inetpub\vhosts\Orchard-Dev\1.7.1-Coevery-30-10-13\src\Orchard\InvokeExtensions.cs:line 39

**Comment by lfurzewaddock** [comment]
Commit: https://github.com/lfurzewaddock/Coevery-Orchard/commit/edb95bf8fa14b01336fbeb8f4fe39eeff53a0ac3 has fixed this bug.
